[env:imercam_x]
platform = espressif32
board = m5stack-timer-cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv
lib_deps = h2zero/NimBLE-Arduino @ ^1.4.3
